Bit of organization and cleanup

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,11 +1,4 @@
 #!/bin/bash
-#
-# Copyright © 2014 Jesse 'Jeaye' Wilkerson
-# See licensing in LICENSE file, or at:
-#   http://www.opensource.org/licenses/MIT
-#
-# File: configure
-# Author: Jesse 'Jeaye' Wilkerson
 
 # Re-invoke the configure script
 # and keep the output at bay.
@@ -20,48 +13,65 @@ set -o errexit
 set -o nounset
 
 # Determine system
-UNAME_LINUX=0
-UNAME_CYGWIN=0
-UNAME_OSX=0
-UNAME=$(uname)
-if [ "$UNAME" = "Linux" ];
+uname_linux=0
+uname_cygwin=0
+uname_osx=0
+uname=$(uname)
+if [ "$uname" = "Linux" ];
 then
-  UNAME_LINUX=1
-elif [ "$UNAME" = "Darwin" ];
+  uname_linux=1
+elif [ "$uname" = "Darwin" ];
 then
-  UNAME_OSX=1
+  uname_osx=1
 elif [ "$(uname -o)" = "Cygwin" ];
 then
-  UNAME_CYGWIN=1
+  uname_cygwin=1
 else
-  echo "Invalid uname ($UNAME): Unsuppported platform" 1>&2
+  echo "Invalid uname ($uname): unsuppported platform" 1>&2
   exit 1
 fi
 
 log() { echo "$@" 1>&2; }
 log_start() { printf "$@" 1>&2; }
 log_end() { echo "$@" 1>&2; }
+log_exit() { echo "$@" 1>&2; exit 1; }
 
-PROJECT=jeayeson
-log "Configuring ${PROJECT}"
+project=jeayeson
+log "Configuring ${project}"
 
-PREFIX=/usr/local
-DATAROOTDIR=$PREFIX/include/jeayeson
-THREADS=4
-CXX_PLATFORM_FLAGS=
-LD_PLATFORM_LIBS=
-if [ "1" -eq "$UNAME_LINUX" ];
+prefix=/usr/local
+includedir="$prefix/include"
+threads=4
+cxx_platform_flags=
+ld_platform_libs=
+
+# Project-specific flags
+
+if [ "1" -eq "$uname_linux" ];
 then
   log "Platform: Linux"
-elif [ "1" -eq "$UNAME_OSX" ];
+elif [ "1" -eq "$uname_osx" ];
 then
   log "Platform: OS X"
-  CXX_PLATFORM_FLAGS="-stdlib=libc++ -I/opt/local/include"
-  LD_PLATFORM_LIBS="-lc++"
-elif [ "1" -eq "$UNAME_CYGWIN" ];
+  cxx_platform_flags="-stdlib=libc++ -I/opt/local/include"
+  ld_platform_libs="-lc++"
+elif [ "1" -eq "$uname_cygwin" ];
 then
   log "Platform: Cygwin (NOT TESTED)"
 fi
+
+function show_help
+{
+  log "Usage: $0 [OPTION...]"
+  log
+  log "General:"
+  log "  -h, --help                                   Show this help message"
+  log "  --prefix=[/usr/local]                        Set installation prefix"
+  log "  --includedir=[/usr/local/include]            Set include prefix"
+  log "  --threads=[4]                                Set number of threads to use"
+  log
+  exit 0
+}
 
 # Parse params
 for i in "$@"
@@ -69,46 +79,43 @@ do
   case $i in
     --prefix)
       shift
-      PREFIX="$1"
-      DATAROOTDIR=$PREFIX/include
+      prefix="$1"
+      includedir=$PREFIX/include
       shift
       ;;
     --prefix=*)
-      PREFIX="${i#*=}"
-      DATAROOTDIR=$PREFIX/include
+      prefix="${i#*=}"
+      includedir=$PREFIX/include
       shift
       ;;
 
-    --datarootdir)
+    --includedir)
       shift
-      DATAROOTDIR="$1"
+      includedir="$1"
       shift
       ;;
-    --datarootdir=*)
-      DATAROOTDIR="${i#*=}"
+    --includedir=*)
+      includedir="${i#*=}"
       shift
       ;;
 
     --threads)
       shift
-      THREADS=$1
+      threads=$1
       shift
       ;;
     --threads=*)
-      THREADS=${i#*=}
+      threads=${i#*=}
       shift
       ;;
 
-    --help*)
-      log "Usage: $0 [OPTION...]"
-      log
-      log "  --help                                       Show this help message"
-      log "  --prefix=[/usr/local]                        Set installation prefix"
-      log "  --datarootdir=[/usr/local/include/jeayeson]  Set data root prefix"
-      log "  --threads=[4]                                Set number of threads to use"
-      log
-      exit 0
+    -h)
+      show_help
       ;;
+    --help*)
+      show_help
+      ;;
+
     *)
       # Unknown option
       ;;
@@ -117,21 +124,23 @@ done
 
 # Update after params
 log
-log "Install prefix: $PREFIX"
-log "Install data prefix: $DATAROOTDIR"
-log "Compilation threads: $THREADS"
+log "Install prefix: $prefix"
+log "Install include prefix: $includedir"
+log "Compilation threads: $threads"
 log
 
 # Configure the makefile
-log "Populating Makefile"
+log_start "Populating Makefile..."
 rm -f Makefile
-sed "s#%CXX_PLATFORM_FLAGS%#${CXX_PLATFORM_FLAGS}#" ./Makefile.in |\
-sed "s#%LD_PLATFORM_LIBS%#${LD_PLATFORM_LIBS}#" |\
-sed "s#%PREFIX%#${PREFIX}#" |\
-sed "s#%DATAROOTDIR%#${DATAROOTDIR}#" |\
-sed "s#%THREADS%#${THREADS}#" > Makefile
+sed "s#%CXX_PLATFORM_FLAGS%#${cxx_platform_flags}#" ./Makefile.in |\
+sed "s#%LD_PLATFORM_LIBS%#${ld_platform_libs}#" |\
+sed "s#%PREFIX%#${prefix}#" |\
+sed "s#%INCLUDEDIR%#${includedir}#" |\
+sed "s#%PROJECT%#${project}#" |\
+sed "s#%THREADS%#${threads}#" > Makefile
+log_end " done"
 
-log "Done configuring ${PROJECT}"
+log "Done configuring ${project}"
 
 # Describe next steps
 log
